name: Our Workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fe-dev # checkout v3가 제일 최신 커밋을 의미함.
        with:
          path: vite-project
      - run: ls -al vite-project
