name: fe-dev 브랜치 깃허브 페이지스에 배포
on:
  push: # fe-dev 브랜치에 pr이 Merge 됐을 때 실행해라!
    branches: ["main"]
    
jobs:
  deploy:
    runs-on: ubuntu-latest    
    steps:
      - name: Install pnpm
        run: npm install -g pnpm
      - uses: actions/checkout@v3
      - run: ls -al
      - run: cd vite-project; ls -al
      - name: Install Dependencies # 의존 파일 설치
        run: cd vite-project; pnpm install
      - name: 빌드 실행
        run: cd vite-project; pnpm run build
        
