name: fe-dev 브랜치 깃허브 페이지스에 배포
on:
  pull_request: # fe-dev 브랜치에 pr이 Merge 됐을 때 실행해라!
    branches: ["fe-dev"]
    types: closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        run: npm install -g pnpm
      - uses: actions/checkout@v3 # 최신 버전의 커밋 가져와라
      - run: ls -al
      - run: cd vite-project; ls -al
      - run: git switch fe-dev
      - name: Install Dependencies # 의존 파일 설치
        run: cd vite-project; pnpm install # vite-project 폴더에 들어가서 의존성 설치해라
      - name: 빌드 실행
        run: cd vite-project; pnpm run build # vite-project 폴더에 들어가서 build 해라
      - name: github identity 설정 이메일
        run: git config --global user.email "mahwin7085@gmail.com"
      - name: github identity 설정 이름
        run: git config --global user.name "youseock"
      - name: Deploy to gh-pages # vite-project 폴더에 들어가서 deploy해라
        run: cd vite-project; pnpm run deploy
