name: fe-dev 브랜치 깃허브 페이지스에 배포
on:
  pull_request: # fe-dev 브랜치에 pr이 Merge 됐을 때 실행해라!
    branches: ["fe-dev"]
    types: closed

#  GITHUB_TOKEN의 권한을 설정하여 GitHub Pages에 배포할 수 있도록 함
# permissions:
#   contents: read
#   pages: write
#   id-token: write

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        run: npm install -g pnpm
      - uses: actions/checkout@v3 # 최신 버전의 커밋 가져와라
      - name: ls -al
        run: cd vite-project; ls -al
      - name: branch 이동 fe-dev
        run: git switch fe-dev
      - name: Install Dependencies # 의존 파일 설치
        run: cd vite-project; pnpm install # vite-project 폴더에 들어가서 의존성 설치해라
      - name: 빌드 실행
        run: cd vite-project; pnpm run build # vite-project 폴더에 들어가서 build 해라
      - name: 빌드 파일 확인
        run: cd dist; ls -al # dist 폴더에 들어가서 빌드 파일 확인해라
      # - name: 서버 실행
      # run: cd vite-project; npm run preview # vite-project 폴더에 들어가서 build 해라

      # - name: Setup Pages
      #   uses: actions/configure-pages@v3
      # - name: ls -al
      #   run: cd vite-project; ls -al
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v2
      #   with:
      #     # dist 디렉터리 업로드
      #     path: "./vite-project/dist"
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v2
